### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by humphd** [Reza9472/StaticSiteGenerator#3]
The current installation instructions recommend installing things globally (i.e., using `-g`).  I would avoid this, and prefer local installations for node packages in all cases.  Also, you mention `npm install commander` but using `npm install` is all you need, since `commander` is listed in your `package.json` dependencies.

**Comment by Reza9472** [comment]
@humphd Thank you for the suggestions.
The changes have been added to my instructions
