### ISSUE TITLE
Fix licensing

### ISSUE THREAD

**Issue by humphd** [Reza9472/StaticSiteGenerator#5]
Two issues I notice with the license:

1. The `license` field doesn't match your license: https://github.com/Reza9472/StaticSiteGenerator/blob/main/package.json#L13 should be `MIT`
2. You should use a proper name/email vs. a username in https://github.com/Reza9472/StaticSiteGenerator/blob/main/LICENSE#L3

**Comment by Reza9472** [comment]
Fixed.
Thank you!
